### ISSUE TITLE
Start planning milestone 2

### ISSUE THREAD

**Issue by catvec** [cs326-final-bet/cs326-final-bet#10]
[Assignment Google Doc](https://docs.google.com/document/d/1U1iXfvlNBNziRkxjKIaDFUqQ8vpYtjOBgWLPY3GRJxg/edit).  

Let's pin down a time to meet and discuss milestone 2.

As far as I can tell we need to plan the following:

- [x] Description of every API endpoint
  - First we should list what action must take place on every resource
  - Each action will then be an API endpoint
  - Divide these endpoints among us
- ~~Create module which interacts with database~~
- [x] Mock out every API endpoint
- [x] Make frontend interactive and call API appropriately
- [x] Deploy to Heroku (Already done)

**Comment by catvec** [comment]
- Get areas
  - For certain extent on map
- Strava web hook
  - Creates workout & track & areas

**Comment by pgoss** [comment]
Get:

- Work Out Data: startTime (Date), finishTime (Date), totalTime (Number), date

- Track: id (Number), long (Number), lat (Number), comments (String), likes (Number)

Create User

**Comment by DTooth** [comment]
Get:  User Data
- userID (Number)
- userName (String)
- userPassword (String)
- userStats (JSON Object)
- email (String)
- friendsList (Number[])

**Comment by catvec** [comment]
- POST Login endpoint

**Comment by catvec** [comment]
- POST Add friend

**Comment by catvec** [comment]
- GET Compare user stats

**Comment by pgoss** [comment]
UPDATE User information

**Comment by catvec** [comment]
- POST Add comment to track

**Comment by catvec** [comment]
- POST Like track

**Comment by pgoss** [comment]
CREATE User

**Comment by catvec** [comment]
Dylan:

- POST Add friend
- GET Compare friend
- UPDATE user info
- GET USer

Patrick:

- POST Create user
- POST Login endpoint
- GET Workout
- GET Track

Noah:

- GET Areas
- POST Strava web hook
- POST Like
- POST Comment

For each:

- HTTP method (ex., `POST` or `GET`)
- HTTP path (ex., `/users`)
- URL parameters (ex., `/users/:id` or `/users?foo=true`)
- Request body specification if `POST` or `UPDATE`
- Response body specification
